name: 🌐 Build Web
on: [workflow_call, workflow_dispatch]

jobs:
  build:
    name: Web WebAssembly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Build
        run: |
          python -m pip install scons
          git clone --depth=1 https://github.com/emscripten-core/emsdk
          pushd emsdk
          ./emsdk install 3.1.64
          ./emsdk activate 3.1.64
          source $(pwd)/emsdk_env.sh
          popd
          scons platform=web

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-web
          path: |
            addons/CameraServerExtension/*/libcameraserver-extension.web.wasm
