name: 🏁 Build Windows
on: [workflow_call, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, x86_32, x86_64]
    name: Windows ${{ matrix.arch }}
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Setup
        run: |
          python -m pip install scons

      - name: Build
        run: |
          scons arch=${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-windows-${{ matrix.arch }}
          path: |
            addons/CameraServerExtension/*/libcameraserver-extension.windows.dll
