name: 🍎 Build macOS
on: [workflow_call, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64", "x86_64"]
        include:
          - arch: "arm64"
            sconsflags: macos_deployment_target=11.0
          - arch: "x86_64"
            sconsflags: macos_deployment_target=10.13
    name: macOS ${{ matrix.arch }}
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Setup
        run: |
          python -m pip install scons

      - name: Build
        run: |
          scons arch=${{ matrix.arch }} ${{ matrix.sconsflags }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-macos-${{ matrix.arch }}
          path: |
            addons/CameraServerExtension/*/libcameraserver-extension.macos.dylib
